make;
make clean;
touch infile;
touch infile2;
touch no_right_infile;
touch no_right_outfile;
chmod 000 no_right_infile;
chmod 000 no_right_outfile;
echo "          ----- ERROR MANAGEMENT -----            ";
echo "$(tput setaf 2)Not enough arguments :\n$(tput setaf 7)";
./pipex;
echo "$(tput setaf 2)Too much arguments :\n$(tput setaf 7)";
./pipex infile "ls -l" "cat" "pwd" outfile;
echo "$(tput setaf 2)Infile does not exist :\n$(tput setaf 7)";
./pipex nono "ls -l" "cat" outfile;
echo "$(tput setaf 2)No right to access infile :\n$(tput setaf 7)";
./pipex no_right_infile "ls -l" "cat" outfile;
echo "$(tput setaf 2)No right to access outfile :\n$(tput setaf 7)";
./pipex infile "ls -l" "cat" no_right_outfile;
echo "$(tput setaf 2)Command does not exist :\n$(tput setaf 7)";
./pipex infile "nini" "nono" outfile;
echo "$(tput setaf 2)No command :\n$(tput setaf 7)";
./pipex infile "" "" outfile;
echo "$(tput setaf 2)env is empty:\n$(tput setaf 7)";
env -i ./pipex /dev/urandom "cat" "ls" outfile;

echo "           ----- NORMAL COMMANDS -----             ";
echo "$(tput setaf 2)cat && ls -l\n$(tput setaf 7)";
./pipex infile "cat" "ls -l" outfile;cat outfile;
< infile2 cat | ls -l > outfile2;cat outfile2;
echo "$(tput setaf 2)touch && pwd\n$(tput setaf 7)";
./pipex infile "touch test.txt" "pwd" outfile;cat outfile;
echo "$(tput setaf 2)echo && cat\n$(tput setaf 7)";
./pipex infile "echo salut les amis test" "cat" outfile;cat outfile;
echo "$(tput setaf 2)mkdir && echo$(tput setaf 7)";
./pipex infile "mkdir dossier_test" "echo le test est effectué" outfile;cat outfile;
echo "$(tput setaf 2)ls && ls$(tput setaf 7)";
./pipex infile "ls" "ls" outfile;cat outfile;
echo "$(tput setaf 2)cat && cat$(tput setaf 7)";
./pipex infile "cat" "cat" outfile;cat outfile;
echo "$(tput setaf 2)echo nono echo lolo$(tput setaf 7)";
./pipex infile "echo nono" "echo lolo" outfile;cat outfile;
echo "$(tput setaf 2)grep lolo && head$(tput setaf 7)";
./pipex infile "echo lolo" "wc -l" outfile;cat outfile;
echo "$(tput setaf 2)         ----- TEST OVER -----       $(tput setaf 7)";
